Convert datetime to ISO 8601 in JSON response
Same as in f2c21669dd966e70fcd21ef8c39069a5e779ad56 compiler throws next error:
```
TypeError: Object of type 'Datetime' is not JSON serializable
```

This change converts UUIDs to strings in a ISO-8601 format before returning final JSON object.
Useful for us, since we intend to use ISO-8601 datetimes across all application occurrences.